spring:
  cache:
    type: jcache
    jcache:
      provider: org.redisson.jcache.JCachingProvider
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${POSTGRES_AUTH_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          emailVerificationEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.EmailVerificationEvent,
          passwordResetEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.PasswordResetEvent,
          userRegisteredEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.UserRegisteredEvent,
          updateWorkspaceMemberDataEvent:com.baskaaleksander.nuvine.infrastructure.dto.UpdateWorkspaceMemberDataEvent

bucket4j:
  enabled: true
  cache-to-use: jcache
  methods:
    - name: login_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
          - capacity: 20
            time: 1
            unit: hours

    - name: register_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: hours

    - name: logout_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
          - capacity: 20
            time: 1
            unit: hours

    - name: profile_update_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 15
            unit: minutes

    - name: refresh_token_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
          - capacity: 20
            time: 15
            unit: minutes

    - name: email_change_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 3
            time: 15
            unit: minutes

    - name: email_verify_request_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 3
            time: 15
            unit: minutes

    - name: email_verify_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 3
            time: 15
            unit: minutes

    - name: password_change_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 3
            time: 15
            unit: minutes

    - name: forgot_password_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 3
            time: 15
            unit: minutes

    - name: reset_password_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 3
            time: 15
            unit: minutes

    - name: check_password_reset_token_limit
      cache-name: auth-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
          - capacity: 20
            time: 15
            unit: minutes
server:
  port: 8040

keycloak:
  server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans