spring:
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${CHAT_DB_URL}
    username: ${CHAT_DB_USER}
    password: ${CHAT_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

chat:
  keycloak:
    auth-server-url: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
    client-id: chat-service
    client-secret: ${KEYCLOAK_CHAT_SERVICE_SECRET}

management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
