spring:
  datasource:
    url: ${POSTGRES_CHAT_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

chat:
  keycloak:
    auth-server-url: http://localhost:9098/realms/nuvine/protocol/openid-connect/token
    client-id: chat-service
    client-secret: ${KEYCLOAK_CHAT_SERVICE_SECRET}
server:
  port: 8110