file-storage:
  keycloak:
    auth-server-url: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
    client-id: file-storage-service
    client-secret: ${KEYCLOAK_FILE_STORAGE_SERVICE_SECRET}

s3:
  bucket-name: ${MINIO_BUCKET_NAME}
  internal-url: ${MINIO_INTERNAL_URL}
  external-url: ${MINIO_EXTERNAL_URL}
  access:
    name: ${MINIO_ACCESS_NAME}
    secret: ${MINIO_ACCESS_SECRET}
  webhook:
    secret: ${MINIO_WEBHOOK_SECRET}

spring:
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
