file-storage:
  keycloak:
    auth-server-url: http://localhost:9098/realms/nuvine/protocol/openid-connect/token
    client-id: file-storage-service
    client-secret: ${KEYCLOAK_FILE_STORAGE_SERVICE_SECRET}

s3:
  bucket-name: ${MINIO_BUCKET_NAME}
  internal-url: ${MINIO_INTERNAL_URL}
  external-url: ${MINIO_EXTERNAL_URL}
  access:
    name: ${MINIO_ACCESS_NAME}
    secret: ${MINIO_ACCESS_SECRET}
  webhook:
    secret: ${MINIO_WEBHOOK_SECRET}
spring:
  cache:
    type: jcache
    jcache:
      provider: org.redisson.jcache.JCachingProvider
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  cloud:
    openfeign:
      okhttp:
        enabled: true

server:
  port: 8070

bucket4j:
  enabled: true
  cache-to-use: jcache
  methods:
    - name: download_limit
      cache-name: file-storage-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 5
            unit: minutes
    - name: upload_limit
      cache-name: file-storage-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 5
            unit: minutes