spring:
  cache:
    type: jcache
    jcache:
      provider: org.redisson.jcache.JCachingProvider
  cloud:
    openfeign:
      okhttp:
        enabled: true

server:
  port: 8070

bucket4j:
  enabled: true
  cache-to-use: jcache
  methods:
    - name: download_limit
      cache-name: file-storage-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 5
            unit: minutes
    - name: upload_limit
      cache-name: file-storage-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 5
            unit: minutes
