spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: admin-users
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/admin/users/**
              filters:
                - RewritePath=/api/v1/admin/users(?<segment>/?.*), /api/v1/auth/users${segment}
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: auth-service-internal
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/internal/auth/users/**
            - id: workspace-service-workspaces
              uri: lb://workspace-service
              predicates:
                - Path=/api/v1/workspaces/**
            - id: workspace-service-projects
              uri: lb://workspace-service
              predicates:
                - Path=/api/v1/projects/**
            - id: workspace-service-documents
              uri: lb://workspace-service
              predicates:
                - Path=/api/v1/documents/**
            - id: workspace-service-documents-internal
              uri: lb://workspace-service
              predicates:
                - Path=/api/v1/internal/documents/**
            - id: file-storage-service
              uri: lb://file-storage-service
              predicates:
                - Path=/api/v1/files/**
            - id: file-storage-service-internal
              uri: lb://file-storage-service
              predicates:
                - Path=/api/v1/internal/file-storage/**
            - id: ingestion-service-internal
              uri: lb://ingestion-service
              predicates:
                - Path=/api/v1/internal/ingestion/**
            - id: llm-router-service-internal
              uri: lb://llm-router-service
              predicates:
                - Path=/api/v1/internal/llm/**
            - id: vector-service-internal
              uri: lb://vector-service
              predicates:
                - Path=/api/v1/internal/vector/**
            - id: chat-service
              uri: lb://chat-service
              predicates:
                - Path=/api/v1/chat/**
            - id: workspace-service-projects-internal
              uri: lb://workspace-service
              predicates:
                - Path=/api/v1/internal/projects/**
            - id: subscription-service
              uri: lb://subscription-service
              predicates:
                - Path=/api/v1/subscription/**
            - id: workspace-service-workspaces-internal
              uri: lb://workspace-service
              predicates:
                - Path=/api/v1/internal/workspaces/**
server:
  port: 8222