spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: auth-service
              uri: lb:http://auth-service
              predicates:
                - Path=/api/v1/auth/**

server:
  port: 8222