spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: admin-users
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/admin/users/**
              filters:
                - RewritePath=/api/v1/admin/users(?<segment>/?.*), /api/v1/auth/users${segment}
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: workspace-service
              uri: lb://workspace-service
              predicates:
                - Path=/api/v1/workspaces/**
server:
  port: 8222