spring:
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
