file-storage:
  keycloak:
    auth-server-url: http://localhost:9098/realms/nuvine/protocol/openid-connect/token
    client-id: ingestion-service
    client-secret: ${KEYCLOAK_INGESTION_SERVICE_SECRET}

spring:
  datasource:
    url: ${POSTGRES_INGESTION_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      group-id: ingestion-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.baskaaleksander.nuvine.infrastructure.messaging.dto"
        spring.json.type.mapping: >
          documentUploadedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.DocumentUploadedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.baskaaleksander.nuvine.infrastructure.messaging.dto"
        spring.json.type.mapping:

s3:
  bucket-name: ${MINIO_BUCKET_NAME}
  internal-url: ${MINIO_INTERNAL_URL}
  access:
    name: ${MINIO_ACCESS_NAME}
    secret: ${MINIO_ACCESS_SECRET}
  webhook:
    secret: ${MINIO_WEBHOOK_SECRET}

server:
  port: 8080