ingestion:
  keycloak:
    auth-server-url: http://localhost:9098/realms/nuvine/protocol/openid-connect/token
    client-id: ingestion-service
    client-secret: ${KEYCLOAK_INGESTION_SERVICE_SECRET}

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${POSTGRES_INGESTION_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

s3:
  bucket-name: ${MINIO_BUCKET_NAME}
  internal-url: ${MINIO_INTERNAL_URL}
  access:
    name: ${MINIO_ACCESS_NAME}
    secret: ${MINIO_ACCESS_SECRET}
  webhook:
    secret: ${MINIO_WEBHOOK_SECRET}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
