ingestion:
  keycloak:
    auth-server-url: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
    client-id: ingestion-service
    client-secret: ${KEYCLOAK_INGESTION_SERVICE_SECRET}

spring:
  data:
    redis:
      host: nuvine_redis
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${INGESTION_DB_URL}
    username: ${INGESTION_DB_USER}
    password: ${INGESTION_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

s3:
  bucket-name: ${MINIO_BUCKET_NAME}
  internal-url: ${MINIO_INTERNAL_URL}
  access:
    name: ${MINIO_ACCESS_NAME}
    secret: ${MINIO_ACCESS_SECRET}
  webhook:
    secret: ${MINIO_WEBHOOK_SECRET}

management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
