spring:
  datasource:
    url: ${LLM_ROUTER_DB_URL}
    username: ${LLM_ROUTER_DB_USER}
    password: ${LLM_ROUTER_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

openai:
  api-key: ${OPENAI_API_KEY}

openrouter:
  api-key: ${OPENROUTER_API_KEY}

api-key:
  openai: ${OPENAI_API_KEY}

management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
