spring:
  datasource:
    url: ${POSTGRES_LLM_ROUTER_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      group-id: vector-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.baskaaleksander.nuvine.infrastructure.messaging.dto"
        spring.json.type.mapping: >
          embeddingRequestEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.EmbeddingRequestEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.baskaaleksander.nuvine.infrastructure.messaging.dto"
        spring.json.type.mapping: >
          embeddingCompletedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.EmbeddingCompletedEvent

server:
  port: 8090

openai:
  base-url: https://api.openai.com/v1
  api-key: ${OPENAI_API_KEY}
  embedding-model: text-embedding-3-small

openrouter:
  base-url: https://openrouter.ai/api/v1
  api-key: ${OPENROUTER_API_KEY}

api-key:
  openai: ${OPENAI_API_KEY}

resilience4j:
  circuitbreaker:
    configs:
      openrouter-model:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      openai-embeddings:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,circuitbreakers,circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans