spring:
  datasource:
    url: ${POSTGRES_LLM_ROUTER_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

openai:
  api-key: ${OPENAI_API_KEY}

openrouter:
  api-key: ${OPENROUTER_API_KEY}

api-key:
  openai: ${OPENAI_API_KEY}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
