spring:
  cache:
    type: jcache
    jcache:
      provider: org.redisson.jcache.JCachingProvider
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      okhttp:
        enabled: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.metrics.push: false
        spring.json.add.type.headers: true
        spring.json.trusted.packages: "com.baskaaleksander.nuvine.infrastructure.messaging.dto"
        spring.json.type.mapping: >
          paymentActionRequiredEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.PaymentActionRequiredEvent,
          dlqMessage:com.baskaaleksander.nuvine.infrastructure.messaging.dto.DlqMessage,
          workspaceDeletedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.WorkspaceDeletedEvent,
          workspaceDeletedDlqMessage:com.baskaaleksander.nuvine.infrastructure.messaging.dto.WorkspaceDeletedDlqMessage
    consumer:
      group-id: subscription-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        enable.metrics.push: false
        spring.json.trusted.packages: "com.baskaaleksander.nuvine.infrastructure.messaging.dto"
        spring.json.type.mapping: >
          logTokenUsageEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.LogTokenUsageEvent,
          workspaceDeletedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.WorkspaceDeletedEvent,
          workspaceDeletedDlqMessage:com.baskaaleksander.nuvine.infrastructure.messaging.dto.WorkspaceDeletedDlqMessage

topics:
  usage-logs-dlq-topic: usage-logs-dlq
  usage-logs-dead-letter-topic: usage-logs-dead-letter
  workspace-deleted-topic: workspace-deleted
  workspace-deleted-dlq-topic: workspace-deleted-dlq
  workspace-deleted-dead-letter-topic: workspace-deleted-dead-letter

dlq:
  usage-logs:
    max-retry-attempts: 10
    processing-delay-ms: 300000
    batch-size: 100
  workspace-deleted:
    max-retry-attempts: 10
    processing-delay-ms: 300000
    batch-size: 100

server:
  port: 8120

bucket4j:
  enabled: true
  cache-to-use: jcache
  methods:
    - name: payment_session_limit
      cache-name: subscription-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 15
            unit: minutes
    - name: customer_portal_limit
      cache-name: subscription-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 15
            unit: minutes
