spring:
  datasource:
    url: ${POSTGRES_SUBSCRIPTION_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

stripe:
  api-key: ${STRIPE_API_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

subscription:
  keycloak:
    auth-server-url: http://localhost:9098/realms/nuvine/protocol/openid-connect/token
    client-id: subscription-service
    client-secret: ${KEYCLOAK_SUBSCRIPTION_SERVICE_SECRET}

server:
  port: 8120