spring:
  cache:
    type: jcache
    jcache:
      provider: org.redisson.jcache.JCachingProvider
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      group-id: vector-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.baskaaleksander.nuvine.infrastructure.messaging.dto"
        spring.json.type.mapping: >
          vectorProcessingRequestEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.VectorProcessingRequestEvent,
          embeddingCompletedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.EmbeddingCompletedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.baskaaleksander.nuvine.infrastructure.messaging.dto"
        spring.json.type.mapping: >
          embeddingRequestEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.EmbeddingRequestEvent,
          vectorProcessingCompletedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.VectorProcessingCompletedEvent,
          embeddingCompletedDlqMessage:com.baskaaleksander.nuvine.infrastructure.messaging.dto.EmbeddingCompletedDlqMessage,
          vectorProcessingRequestDlqMessage:com.baskaaleksander.nuvine.infrastructure.messaging.dto.VectorProcessingRequestDlqMessage

qdrant:
  port: 6334
  apiKey: null
  collection: nuvine_collection

server:
  port: 8100

topics:
  embedding-completed-dlq-topic: embedding-completed-dlq
  embedding-completed-dead-letter-topic: embedding-completed-dead-letter
  vector-processing-request-dlq-topic: vector-processing-request-dlq
  vector-processing-request-dead-letter-topic: vector-processing-request-dead-letter

dlq:
  embedding-completed:
    max-retry-attempts: 10
    processing-delay-ms: 300000
    batch-size: 100
  vector-processing-request:
    max-retry-attempts: 10
    processing-delay-ms: 300000
    batch-size: 100
