spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${POSTGRES_WORKSPACE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

keycloak:
  auth-server-url: http://localhost:9098/realms/nuvine/protocol/openid-connect/token
  client-id: workspace-service
  client-secret: ${KEYCLOAK_WORKSPACE_SERVICE_SECRET}

application:
  config:
    auth-internal-url: http://localhost:8222/api/v1/internal/auth

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
