spring:
  cache:
    type: jcache
    jcache:
      provider: org.redisson.jcache.JCachingProvider
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${POSTGRES_WORKSPACE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      group-id: vector-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.baskaaleksander.nuvine.infrastructure.messaging.dto"
        spring.json.type.mapping: >
          documentIngestionCompletedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.DocumentIngestionCompletedEvent,
          updateWorkspaceMemberDataEvent:com.baskaaleksander.nuvine.infrastructure.dto.UpdateWorkspaceMemberDataEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          workspaceMemberAddedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.WorkspaceMemberAddedEvent,
          documentUploadedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.DocumentUploadedEvent,
          workspaceMemberInvitedEvent:com.baskaaleksander.nuvine.infrastructure.messaging.dto.WorkspaceMemberInvitedEvent,
          documentIngestionDlqMessage:com.baskaaleksander.nuvine.infrastructure.messaging.dto.DocumentIngestionDlqMessage
keycloak:
  auth-server-url: http://localhost:9098/realms/nuvine/protocol/openid-connect/token
  client-id: workspace-service
  client-secret: ${KEYCLOAK_WORKSPACE_SERVICE_SECRET}

application:
  config:
    auth-internal-url: http://localhost:8222/api/v1/internal/auth
server:
  port: 8060

topics:
  document-ingestion-dlq-topic: document-ingestion-dlq
  document-ingestion-dead-letter-topic: document-ingestion-dead-letter

dlq:
  document-ingestion:
    max-retry-attempts: 10
    processing-delay-ms: 300000
    batch-size: 100

bucket4j:
  enabled: true
  cache-to-use: jcache
  methods:
    - name: create_document_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 5
            unit: minutes

    - name: update_document_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 1
            unit: minutes
          - capacity: 100
            time: 1
            unit: hours

    - name: delete_document_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
          - capacity: 50
            time: 1
            unit: hours

    - name: document_upload_completed_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 1
            unit: minutes
          - capacity: 100
            time: 1
            unit: hours

    - name: document_status_update_internal_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 1
            unit: minutes
          - capacity: 100
            time: 1
            unit: hours

    - name: respond_to_invitation_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
          - capacity: 20
            time: 1
            unit: hours

    - name: create_project_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 1
            unit: minutes
          - capacity: 100
            time: 1
            unit: hours

    - name: update_project_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 1
            unit: minutes
          - capacity: 100
            time: 1
            unit: hours

    - name: delete_project_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
          - capacity: 50
            time: 1
            unit: hours

    - name: create_workspace_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
          - capacity: 50
            time: 1
            unit: hours

    - name: update_workspace_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 1
            unit: minutes
          - capacity: 100
            time: 1
            unit: hours

    - name: delete_workspace_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 2
            time: 1
            unit: minutes
          - capacity: 20
            time: 1
            unit: hours

    - name: workspace_billing_tier_update_internal_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 1
            unit: minutes
          - capacity: 100
            time: 1
            unit: hours

    - name: invite_workspace_member_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
          - capacity: 50
            time: 1
            unit: hours

    - name: remove_workspace_member_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 1
            unit: minutes
          - capacity: 100
            time: 1
            unit: hours

    - name: update_workspace_member_role_limit
      cache-name: workspace-service-buckets
      rate-limit:
        bandwidths:
          - capacity: 10
            time: 1
            unit: minutes
          - capacity: 100
            time: 1
            unit: hours